### ISSUE TITLE
사용자 정보 수정 관련 이슈

### ISSUE THREAD

**Issue by ingkoon** [UPF2022SS-464/KoonsDiary-Spring#10]
사용자의 정보를 수정하는 부분은 닉네임 부분밖에 없다.
하지만 이 닉네임의 변경에 의한 영향을 고려해야 할 필요가 있으며, 특히 사용자가 속한 공유일기 그룹 내에서 사용자가 작성한 일기에 대한 
닉네임을 바꾸어 적용시킬 필요가 있다.

예를 들어 koon이라는 유저가 공유일기(1)에 1개의 글을 작성한 상태에서 nook으로 닉네임 변경을 수행했을 경우, 
공유일기(1)에서 나타나는 모든 koon이라는 닉네임이 nook으로 바뀌어야 한다.

이부분을 고려해서 추후 api 수정 시에 기능을 추가할 수 있도록 하자

**Comment by svclaw2000** [comment]
RDBMS를 사용하고 있기 때문에 조회 시점에 공유일기와 사용자 테이블을 join해서 가져오면 수정된게 그대로 반영되지 않을까요??

**Comment by ingkoon** [comment]
아뿔싸... 너무 1차원적으로 생각했네요 감사합니다.
